// <auto-generated />
using System;
using FinanceDashboard.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceDashboard.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824162004_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceDashboard.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.BudgetGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("citext");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Category")
                        .IsUnique();

                    b.ToTable("BudgetGoals", t =>
                        {
                            t.HasCheckConstraint("CK_BudgetGoals_Category_Length", "char_length(\"Category\") <= 60");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.EmailVerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.FinancialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountMask")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InstitutionCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProviderItemId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExternalAccountId");

                    b.HasIndex("UserId", "ProviderItemId");

                    b.HasIndex("UserId", "AccountType", "Provider", "InstitutionName");

                    b.ToTable("FinancialAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_FinancialAccounts_AccountType", "\"AccountType\" IN ('bank_account', 'wallet', 'cash', 'credit_card')");

                            t.HasCheckConstraint("CK_FinancialAccounts_Status", "\"Status\" IN ('disconnected', 'pending', 'connected', 'error')");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.InstallmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountPerInstallmentCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PublicId")
                        .IsUnique();

                    b.ToTable("InstallmentPlans", t =>
                        {
                            t.HasCheckConstraint("CK_InstallmentPlans_Category_Length", "char_length(\"Category\") <= 60");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.NotificationDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationType", "SentAtUtc");

                    b.HasIndex("UserId", "NotificationType", "ReferenceKey")
                        .IsUnique();

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.RecurringRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("citext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastGeneratedDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NextOccurrenceDate")
                        .HasColumnType("date");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TagsCsv")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PublicId")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive", "NextOccurrenceDate");

                    b.ToTable("RecurringRules", t =>
                        {
                            t.HasCheckConstraint("CK_RecurringRules_Category_Length", "char_length(\"Category\") <= 60");

                            t.HasCheckConstraint("CK_RecurringRules_Type", "\"Type\" IN ('income', 'expense')");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("citext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("FinancialAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("InstallmentGroupId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("InstallmentIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("InstallmentPlanId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecurrenceEndDate")
                        .HasColumnType("date");

                    b.Property<string>("RecurrenceGroupId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("RecurringRuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FinancialAccountId");

                    b.HasIndex("InstallmentPlanId");

                    b.HasIndex("RecurringRuleId");

                    b.HasIndex("UserId", "InstallmentGroupId");

                    b.HasIndex("UserId", "RecurrenceGroupId");

                    b.HasIndex("UserId", "Source", "SourceReference");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Category_Length", "char_length(\"Category\") <= 60");

                            t.HasCheckConstraint("CK_Transactions_Source", "\"Source\" IN ('manual', 'import_csv', 'import_ofx', 'bank_sync')");

                            t.HasCheckConstraint("CK_Transactions_Type", "\"Type\" IN ('income', 'expense')");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.TransactionTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("citext");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("TransactionTags", t =>
                        {
                            t.HasCheckConstraint("CK_TransactionTags_Name_Length", "char_length(\"Name\") <= 40");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.TransactionTagLink", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionTagId")
                        .HasColumnType("integer");

                    b.HasKey("TransactionId", "TransactionTagId");

                    b.HasIndex("TransactionTagId");

                    b.ToTable("TransactionTagLinks");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DemoExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EmailGoalAlertsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("GoalAlertThresholdPercent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDemoAccount")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFailedLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MonthlyReportDay")
                        .HasColumnType("integer");

                    b.Property<bool>("MonthlyReportEmailsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("OnboardingOptIn")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("PublicDashboardEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PublicDashboardTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("SessionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicDashboardTokenHash")
                        .IsUnique()
                        .HasFilter("\"PublicDashboardTokenHash\" IS NOT NULL");

                    b.HasIndex("IsDemoAccount", "DemoExpiresAtUtc");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_MonthlyReportDay", "\"MonthlyReportDay\" >= 1 AND \"MonthlyReportDay\" <= 28");
                        });
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.AuditLog", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.BudgetGoal", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("BudgetGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.FinancialAccount", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("FinancialAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.InstallmentPlan", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("InstallmentPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.NotificationDelivery", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.PasswordResetToken", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.RecurringRule", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("RecurringRules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.Transaction", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.FinancialAccount", "FinancialAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceDashboard.Api.Models.InstallmentPlan", "InstallmentPlan")
                        .WithMany("Transactions")
                        .HasForeignKey("InstallmentPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceDashboard.Api.Models.RecurringRule", "RecurringRule")
                        .WithMany("Transactions")
                        .HasForeignKey("RecurringRuleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialAccount");

                    b.Navigation("InstallmentPlan");

                    b.Navigation("RecurringRule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.TransactionTag", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.User", "User")
                        .WithMany("TransactionTags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.TransactionTagLink", b =>
                {
                    b.HasOne("FinanceDashboard.Api.Models.Transaction", "Transaction")
                        .WithMany("TagLinks")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinanceDashboard.Api.Models.TransactionTag", "TransactionTag")
                        .WithMany("TransactionLinks")
                        .HasForeignKey("TransactionTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("TransactionTag");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.FinancialAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.InstallmentPlan", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.RecurringRule", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.Transaction", b =>
                {
                    b.Navigation("TagLinks");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.TransactionTag", b =>
                {
                    b.Navigation("TransactionLinks");
                });

            modelBuilder.Entity("FinanceDashboard.Api.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("BudgetGoals");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("FinancialAccounts");

                    b.Navigation("InstallmentPlans");

                    b.Navigation("NotificationDeliveries");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RecurringRules");

                    b.Navigation("TransactionTags");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
